### ISSUE TITLE
Normalized info

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/xps-analysis#6]
@kjappelbaum concerning the normalized data you removed some fields that I thought were useful.

Don't you think that the range (from / to) and the 'species label' are useful information ?

What about the analyser mode ?

```
  const normalized = {};
  normalized.speciesLabel = meta['species label'];

  const increment = meta['abscissa increment'];
  normalized.from = meta['abscissa start'];
  normalized.to =
    meta['abscissa start'] + increment * (meta.nbOrdinateValues - 1);

  normalized.analyserMode = meta['analyser mode'];
  ```

**Comment by kjappelbaum** [comment]
I removed them because we did not set them in the schema yet. I'll discuss them with Mounir.



On Apr 28, 2021 at 07:24, Luc Patiny ***@***.******@***.***>> wrote:


@kjappelbaum<https://github.com/kjappelbaum> concerning the normalized data you removed some fields that I thought were useful.

Don't you think that the range (from / to) and the 'species label' are useful information ?

What about the analyser mode ?

  const normalized = {};
  normalized.speciesLabel = meta['species label'];
  const increment = meta['abscissa increment'];
  normalized.from = meta['abscissa start'];
  normalized.to =
    meta['abscissa start'] + increment * (meta.nbOrdinateValues - 1);
  normalized.analyserMode = meta['analyser mode'];

**Comment by kjappelbaum** [comment]
added them back now
